Repository DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls, pull requests merged in 2024-08, with the labels that each got.

#22 [Design] #19 - SearchBook UI 구현
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Assets.xcassets/divider.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/gentlemangyodong.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/gentlemangyodong.imageset/gentlemangyodong.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/typo30.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookListRow.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookSearchBar.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/AsyncImage.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
Labels: 구리스, UI

#25 [Design] #21 - DetailBook 뷰 그리기
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Resources/Extensions/Font+.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/BookInfo.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBook.swift
Labels: 제리, UI

#28 [Fix] #26 - PhraseCard를 다른 뷰에서 사용할 수 있게 수정했어요.
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Home/HomeView.swift
  BOOKBBANG/BOOKBBANG/Views/Home/PhraseCard.swift
Labels: 제리, Fix

#32 [Feat] #17 - 도서 검색 API 연결
  .gitignore
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Info.plist
  BOOKBBANG/BOOKBBANG/Models/BookDTO.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookListRow.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookSearchBar.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Config.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/SearchRouter.swift
Labels: 구리스, Feat

#31 Design/#29 - 설정 화면에 들어가는 모든 것을 그려왔어요
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Assets.xcassets/logo/AppleLogo.imageset/AppleLogo.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/logo/AppleLogo.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/logo/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/logo/TeamLogo.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/logo/TeamLogo.imageset/TeamLogo.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Dada_profile.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Dada_profile.imageset/Dada_profile.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Gimli_profile.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Gimli_profile.imageset/Gimli_profile.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Guryss_profile.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Guryss_profile.imageset/Guryss_profile.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Jason_profile.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Jason_profile.imageset/Jason_profile.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Jerrie_profile.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Jerrie_profile.imageset/Jerrie_profile.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Rinda_profile.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Rinda_profile.imageset/Rinda_profile.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Rochelle_profile.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/profile/Rochelle_profile.imageset/Rochelle_profile.png
  BOOKBBANG/BOOKBBANG/Models/TeamMember.swift
  BOOKBBANG/BOOKBBANG/Resources/Extensions/Font+.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/Manual.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/Setting.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/TeamInfo.swift
Labels: 제리, UI

#36 [Design] #23 - CustomNavigationBar View UI 구현
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/CustomNavigationBar.swift
Labels: 구리스, UI

#33 Design/#20 - 구절추가하기의 문구 추가하기와 감상평 추가하기 뷰를 짰어요
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhraseHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhraseTextfield.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughsHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughts.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughtsTextfield.swift
Labels: 김리, UI

#40 Design/#39 - 구절 카테고리추가뷰, 완료축하뷰 구현
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/AddCategoryToPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/FinishAddingPhrase/FinishAddingPhrase.swift
Labels: 김리, UI

#49 [Design]#24-DetailClip . 뷰 그리기
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/App/BOOKBBANGApp.swift
  BOOKBBANG/BOOKBBANG/Assets.xcassets/WaterDropClip.imageset/WaterDropClip 1.png
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClipProfile.swift
Labels: 다다, UI

#42 [Feat] #37 - CoreData를 통한 Book 데이터 저장 구현
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/App/BOOKBBANGApp.swift
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/backDarker.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/backLighter.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/clipBlue.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/clipGreen.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/clipOrange.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/clipPink.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/clipPurple.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/clipRed.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/clipSky.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/clipYellow.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/divider.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/greenMain100.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/greenMain40.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/typo10.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/typo100.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/typo25.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/typo30.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/typo50.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/typo80.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_1.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_1.imageset/fish_1.jpg
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_2.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_2.imageset/fish_2.jpg
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_3.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_3.imageset/fish_3.jpg
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_4.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_4.imageset/fish_4.jpg
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_6.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/fish_6.imageset/fish_6.jpg
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/gentlemangyodong.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/gentlemangyodong.imageset/gentlemangyodong.png
  BOOKBBANG/BOOKBBANG/Models/BOOKBBANG.xcdatamodeld/BOOKBBANG.xcdatamodel/contents
  BOOKBBANG/BOOKBBANG/Models/ClipStyle.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookListRow.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchTestView.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/AsyncImage.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/CustomNavigationBar.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/PersistentController.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/SearchRouter.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ImagesContainer.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ImagesGrid.swift
Labels: 구리스, Feat

#46 [Design] #35 - 빵수증 뷰 그렸어요 근데 매우 뗀석기코드
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Models/BOOKBBANG.xcdatamodeld/BOOKBBANG.xcdatamodel/contents
  BOOKBBANG/BOOKBBANG/Resources/Extensions/Date+.swift
  BOOKBBANG/BOOKBBANG/Resources/Extensions/Font+.swift
  BOOKBBANG/BOOKBBANG/Views/Home/BookList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/EmptyBox.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Home/PhraseCard.swift
  BOOKBBANG/BOOKBBANG/Views/Home/SortingBookPicker.swift
  BOOKBBANG/BOOKBBANG/Views/Home/SortingClipPicker.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/DashLineDivider.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/RankingBooks.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/RankingPhrases.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/ReciptMain.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/ShowRecipt.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/TwoLineDivider.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/Manual.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/Setting.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/TeamInfo.swift
Labels: 제리, UI

#53 [Design] #52 - Edit Book UI 구현
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/BookGenreView.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/ReadStatusBox.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/EditBook.swift
Labels: 로셸, UI

#50 [Design] #34 - 구절 상세뷰 짰습니다.
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/CompleteAddingBook.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/AddCategoryToPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/MultipleClipSelectList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhraseHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhraseTextfield.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughsHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughts.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughtsTextfield.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/CompleteAddingPhrase/CompleteAddingPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/CompleteAddingPhrase/CompleteAddingPhraseHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/DetailPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/DetailPhraseClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/ClipChips.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditClipinPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhraseClipSmallList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhraseShowClip.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/FinishAddingPhrase/FinishAddingPhrase.swift
Labels: 김리, UI

#59 [Fix] #58 - 클립 데이터 연결하기.
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Models/BOOKBBANG.xcdatamodeld/BOOKBBANG.xcdatamodel/contents
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/AddClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/ClipShapeButton.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClipProfile.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/EditClip/EditClip.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/countBooksContainingClip.swift
Labels: 제리, Fix

#63 [Feat] #61 - 구리스 남은 개발 업무처리 ver 1.0
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/typo10.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Models/BookData.swift
  BOOKBBANG/BOOKBBANG/Resources/Extensions/UIApplication+.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/ BookInfoSection.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/AddBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/AddDough.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/CompleteAddingBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/BookInfo.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBookViewModel.swift
  BOOKBBANG/BOOKBBANG/Views/Book/EditBook/EditBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/EditBook/EditBookGenreSection.swift
  BOOKBBANG/BOOKBBANG/Views/Book/EditBook/EditBookInfoSection.swift
  BOOKBBANG/BOOKBBANG/Views/Book/EditBook/EditReadStatusSection.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBook.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Home/PhraseCard.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ViewModel/HomeViewModel.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/AddCategoryToPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhraseTextfield.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughts.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughtsPhraseCard.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughtsTextfield.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/CompleteAddingPhrase/CompleteAddingPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/DetailPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/DetailPhraseClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/ClipChips.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhrase.swift
Labels: 구리스, Feat

#65 [Feat] #62 - guryss, merge, lets go
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Models/BOOKBBANG.xcdatamodeld/BOOKBBANG.xcdatamodel/contents
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/BookInfoSection.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/AddClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/ClipColorButton.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/ClipTextFields.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Components/CustomNavigationBar.swift
  BOOKBBANG/BOOKBBANG/Views/Home/BookList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/AddCategoryToPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/MultipleClipSelectList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/DetailPhrase.swift
Labels: 제리, Feat

#67 [Fix] #66 이모저모 (부제: 즐거운 주말을 맞이하기)
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/BOOKBBANG.entitlements
  BOOKBBANG/BOOKBBANG/Models/BOOKBBANG.xcdatamodeld/BOOKBBANG.xcdatamodel/contents
  BOOKBBANG/BOOKBBANG/Models/BookData.swift
  BOOKBBANG/BOOKBBANG/Models/DoughImage.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/AddDough.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/BookGenreView.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/CompleteAddingBook.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/AddClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/ClipColorButton.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/ClipTextFields.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/TopClipImage.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/ClipData.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/EditClip/EditClip.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/AsyncImage.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/PersistenceController.swift
  BOOKBBANG/BOOKBBANG/Views/Home/BookList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Home/PhraseCard.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ShowBreadInCard.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/AddCategoryToPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/MultipleClipSelectList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/SelectClips.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughtsPhraseCard.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/CompleteAddingPhrase/CompleteAddingPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/ClipsInPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/DetailPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/DetailPhraseClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/FlowLayout.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/ClipChips.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditClipinPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhraseClipSmallList.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhraseShowClip.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/Manual.swift
Labels: 제리, Fix

#68 [Feat] #64 - 전체적인 뷰 연결 및 작업 해치우기
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/App/BOOKBBANGApp.swift
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Baking/Congratulatory_bread.imageset/Congratulatory bread.imageset.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Baking/Congratulatory_bread.imageset/Congratulatory bread.imageset@2x.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Baking/Congratulatory_bread.imageset/Congratulatory bread.imageset@3x.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Baking/Congratulatory_bread.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/launchScreenImage.imageset/launchScreenImage@3x.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/loadingGyodong.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/loadingGyodong.imageset/loadingGyodong.jpg
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/loadingThumbnail.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/dummy/loadingThumbnail.imageset/loadingThumbnail.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/logo/launchScreenImage.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/logo/launchScreenImage.imageset/launchScreenImage@3x.png
  BOOKBBANG/BOOKBBANG/Models/BOOKBBANG.xcdatamodeld/BOOKBBANG.xcdatamodel/contents
  BOOKBBANG/BOOKBBANG/Models/BookData.swift
  BOOKBBANG/BOOKBBANG/Models/ManualChapter.swift
  BOOKBBANG/BOOKBBANG/Models/SettingCategory.swift
  BOOKBBANG/BOOKBBANG/Resources/Extensions/UIApplication+.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookListRow.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/AddClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/ClipTextFields.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/EditClip/EditClip.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/AsyncImage.swift
  BOOKBBANG/BOOKBBANG/Views/Home/BookList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/EmptyBox.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Home/PhraseCard.swift
  BOOKBBANG/BOOKBBANG/Views/Onboarding/Onboarding.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/AddCategoryToPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/SelectClips.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhraseTextfield.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/RankingBooks.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/ReciptMain.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/Manual.swift
Labels: 구리스, Feat, Fix

#70 [Feat] #69 - LiveText 기능 추가 및 레이아웃 수정
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBookSearchBar.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/DataScanner.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/LiveText.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/LiveTextViewModel.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Components/CustomNavigationBar.swift
  BOOKBBANG/BOOKBBANG/Views/Home/BookList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/SelectClips.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhraseScanner.swift
Labels: 구리스, Feat

#72 [Feat] #69 - 나머지 레이아웃 수정 ...
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/SelectClips.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhrase.swift
Labels: 구리스, Feat

#73 [Feat] #71 - 진짜미리 하려고 했는데 돈까스가 식도에 쌓여서 못한 거임
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Assets.xcassets/mainLogo.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/mainLogo.imageset/mainLogo.png
  BOOKBBANG/BOOKBBANG/Models/ManualChapter.swift
  BOOKBBANG/BOOKBBANG/Models/SettingCategory.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBookViewModel.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/AsyncImage.swift
  BOOKBBANG/BOOKBBANG/Views/Home/BookList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/.gitkeep
  BOOKBBANG/BOOKBBANG/Views/Receipt/DashLineDivider.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/RankingBooks.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/ReceiptMain.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/ShowRecipt.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/TwoLineDivider.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/RankingBooks.swift
  BOOKBBANG/BOOKBBANG/Views/Recipt/RankingPhrases.swift
Labels: 제리, Feat

#76 [Fix] #75 - 빵수증 장르 반영
  BOOKBBANG/BOOKBBANG/Views/Receipt/ShowRecipt.swift
Labels: 제리, Fix

#77 [Feat] #74- 빵수증 에펙 파일 추가 및 코드 정리
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Resources/receiptVideo.gif
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchTestView.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/GIFImageView.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/PersistenceController.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/RankingBooks.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/ReceiptMain.swift
Labels: 구리스, Feat
