Repository DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls, pull requests merged in 2024-10, with the labels that each got.

#90 [Design] #89 - 빵수증 출력 로딩뷰 UI 및 애니메이션 구현
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/GIFImageView.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/RankingBooks.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/ReceiptLoading.swift
Labels: 구리스, UI

#92 [Design] #86 - 빵수증과 오늘의빵 기능 수정
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/bookbbangillust.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/bookbbangillust.imageset/bookbbangillust.jpg
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/todaysBreadCover.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/todaysBreadCover.imageset/todaysBreadCover.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/todaysBreadCover2.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/todaysBreadCover2.imageset/todaysBreadCover2.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/badge/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/badge/badge_1.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/badge/badge_1.imageset/badge_1st.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/badge/badge_2.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/badge/badge_2.imageset/badge_2nd.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/badge/badge_3.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/badge/badge_3.imageset/badge_3rd.png
  BOOKBBANG/BOOKBBANG/Resources/Extensions/Date+.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/CompleteAddingBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/EditBook/EditBookGenreSection.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/TopClipImage.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/EditClip/EditClip.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Base/AsyncImage.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/TodaysBread.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/RankingBooks.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/ReceiptMain.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/ShowReceipt.swift
Labels: 제리, Fix

#91 [Release] #87 - 릴리즈 2차 작업 완료
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Assets.xcassets/Color Asset/launchBackground.colorset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/GimliClip/HeartClip.imageset/HeartClip.svg
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/induceAddClip.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/induceAddClip.imageset/induceAddClip.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/induceAddClip.imageset/induceAddClip@2x.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/induceAddClip.imageset/induceAddClip@3x.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/induceAddingBook.imageset/Contents.json
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/induceAddingBook.imageset/induceAddingBook.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/induceAddingBook.imageset/induceAddingBook@2x.png
  BOOKBBANG/BOOKBBANG/Assets.xcassets/NyangSter/induceAddingBook.imageset/induceAddingBook@3x.png
  BOOKBBANG/BOOKBBANG/Info.plist
  BOOKBBANG/BOOKBBANG/Models/BookData.swift
  BOOKBBANG/BOOKBBANG/Resources/Extensions/UIApplication+.swift
  BOOKBBANG/BOOKBBANG/Resources/Extensions/UINavigationController+.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/AddBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/BookGenreView.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/BookInfoSection.swift
  BOOKBBANG/BOOKBBANG/Views/Book/AddBook/CompleteAddingBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBookViewModel.swift
  BOOKBBANG/BOOKBBANG/Views/Book/EditBook/EditBook.swift
  BOOKBBANG/BOOKBBANG/Views/Book/EditBook/EditBookGenreSection.swift
  BOOKBBANG/BOOKBBANG/Views/Book/SearchBook/SearchBook.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/ClipColorButton.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/EditClip/EditClip.swift
  BOOKBBANG/BOOKBBANG/Views/Helpers/Components/CustomProgressBar.swift
  BOOKBBANG/BOOKBBANG/Views/Home/BookList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/Home.swift
  BOOKBBANG/BOOKBBANG/Views/Home/PhraseCard.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ViewModel/HomeViewModel.swift
  BOOKBBANG/BOOKBBANG/Views/Onboarding/Onboarding.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddCategoryToPhrase/AddCategoryToPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddPhrase/AddPhraseScanner.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughts.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/AddThoughts/AddThoughtsPhraseCard.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/CompleteAddingPhrase/CompleteAddingPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/CompleteAddingPhrase/CompleteAddingPhraseHeader.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/DetailPhrase/DetailPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Phrase/EditPhrase/EditPhrase.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/RankingBooks.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/ReceiptMain.swift
  BOOKBBANG/BOOKBBANG/Views/Root/Root.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/Manual.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/Setting.swift
  BOOKBBANG/BOOKBBANG/Views/Setting/TeamInfo.swift
  BOOKBBANG/build/XCBuildData/3c3f11822273cc68bfea2f2fa4579dc6.xcbuilddata/build-request.json
  BOOKBBANG/build/XCBuildData/3c3f11822273cc68bfea2f2fa4579dc6.xcbuilddata/description.msgpack
  BOOKBBANG/build/XCBuildData/3c3f11822273cc68bfea2f2fa4579dc6.xcbuilddata/manifest.json
  BOOKBBANG/build/XCBuildData/3c3f11822273cc68bfea2f2fa4579dc6.xcbuilddata/target-graph.txt
  BOOKBBANG/build/XCBuildData/3c3f11822273cc68bfea2f2fa4579dc6.xcbuilddata/task-store.msgpack
Labels: 구리스, UI, Feat

#96 [Fix] 오늘의 추천빵 기능 수정하고 간격수정
  BOOKBBANG/BOOKBBANG.xcodeproj/project.pbxproj
  BOOKBBANG/BOOKBBANG/Config.xcconfig
  BOOKBBANG/BOOKBBANG/Views/Book/DetailBook/DetailBook.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/AddClip/AddClip.swift
  BOOKBBANG/BOOKBBANG/Views/Clip/DetailClip/DetailClip.swift
  BOOKBBANG/BOOKBBANG/Views/Home/ClipList.swift
  BOOKBBANG/BOOKBBANG/Views/Home/TodaysBread.swift
  BOOKBBANG/BOOKBBANG/Views/Receipt/SelectDate.swift
Labels: 제리, Fix
